### ISSUE TITLE
Add basic Gyro/Accelerometer support

### ISSUE THREAD

**Issue by brainexe** [brainexe/node-metawear#1]

**Comment by AlexDmr** [comment]
Indeed, I would love it too :)

**Comment by onnobos** [comment]
Great work so far. Any idea when the Accelerometer part is ready?

**Comment by brainexe** [comment]
The base implementation of the gyroscope seems to work for me. See examples/gyro.js

Yesterday i started the implementation of the accelerometer sensor in branch "accelerometer". See #6  
But it's far away from stable status. It might me usable end of next week

**Comment by onnobos** [comment]
The gyro is working for me and especially after your last updates it runs much quicker and I get the information directly :-). So far I have created a small node application using socket.io and rgraph for a graph. I will be using this to identify jumps for my volleyball team. The accelerometer will be part of plan. 

Thanks for your work so far. BTW Do you re-engineer from the java application from metawear? I'm really interesting how you came up with your solution.

**Comment by brainexe** [comment]
Hey @onnobos, yes i used the Android Java code as base. 
The two most important files are:
- https://github.com/mbientlab/Metawear-AndroidAPI/blob/master/library/src/main/java/com/mbientlab/metawear/impl/DefaultMetaWearBoard.java
- https://github.com/mbientlab/Metawear-AndroidAPI/blob/master/example/src/main/java/com/mbientlab/metawear/example/MainActivity.java

**Comment by brainexe** [comment]
Sorry for delay, but now I merged the first working implementation of the accelerometer into master #6 
You can try the test script in examples/accelerometer.js

But this is only a rough implementation without possibility to change configuration yet
Open tasks:
- implement correct scaling of result ([reference values](https://github.com/mbientlab/Metawear-AndroidAPI/blob/afc11caa3fb993c5d5341fee4206612ae056e65b/library/src/main/java/com/mbientlab/metawear/module/Bmi160Accelerometer.java))
- configurable MOTION_CONFIG (dataRate/accRange)
- configurable TAP_CONFIG
- configurable ORIENT_CONFIG
- configurable FLAT_CONFIG
- configurable LOW_HIGH_G_CONFIG

Feel free to create a pull request for some missing part. I will create further issues for detailed information. If you need help, just ask
