### ISSUE TITLE
Unable to get accel data with less than 7 Hz

### ISSUE THREAD

**Issue by ibaseta220** [brainexe/node-metawear#36]
Whenever a configure the sampling rate under 7 Hz, the device just stops and doesn't retrieve data.

Edit: I have a MetaWerar C, connected with a Raspberry Pi.

**Comment by alanhortz** [comment]
Hi @ibaseta220 ,

The BMI160 Bosh sensor does not support a sampling under 7Hz. In fact when you supply 7Hz, the finds the closest value which is 0.78125.

To know the exact OUTPUT_DATA_RATE please [check this](https://github.com/brainexe/node-metawear/blob/master/src/registers/accelerometer.js#L47) and if you want to know more about the sensor, this is the [sensor datasheet](http://www.mouser.com/ds/2/783/BST-BMI160-DS000-07-786474.pdf)

Regards,

Alan
