### ISSUE TITLE
sensorFusion quaternion example does not produce values

### ISSUE THREAD

**Issue by hamilton** [brainexe/node-metawear#43]
So happy to find this library! Thank you for putting it together.

I am having trouble running the quaternion example with my Metamotion R unit. I don't have any error raised, but the data streamed are all 0s. Is the code snippet in `/examples` known to work at this point? The other supported examples seem to work fine.

**Comment by alanhortz** [comment]
Hi @hamilton,

Could you provide me the Serial Number, Hardware revision, Firmware revision, Model Number ?

On which platform do you run the example ?

I have encountered the same issue and it is usually solved with a soft reset, I advice you to use either the mobile app and the soft reset function provided.

Regards,

Alan

**Comment by alanhortz** [comment]
Hi @hamilton,

I checked again and it could be something related to the way the configuration is written (in fact not written :), I figured out that the configuration of the sensor is forgotten in the example.

I suggest you the following procedure to write the proper config and then attempt again: 

1) Open the Metawear App (I have tested on IOS not yet on Android)
2) Connect to your MetaMotion R
3) Soft reset the device
4) Connect to your MetaMotion R again ;)
5) Setup the Sensorfusion Mode to NDOF and output to Quaternion
5) Start streaming
6) Stop streaming
7) Disconnect
8) Launch the example again

Please let me know, in the meantime I will check again to make sure the example is properly updated with the right code or I will fix the issue with the configuration.

**Helpful information** 
Could you provide me the Serial Number, Hardware revision, Firmware revision, Model Number ?
On which platform do you run the example ?

Alan

BTW : You can follow the progress mad on version 0.3.8 [here](https://github.com/alanhortz/node-metawear/tree/sensorfusion)

**Comment by alanhortz** [comment]
@hamilton 

I just created a new branch regarding the configuration issue.

Would you please test this example ? https://github.com/brainexe/node-metawear/blob/issue-43/examples/sensorFusion.js

Please perform a soft reset and try again with that exact example code.

Thanks,

Alan

**Comment by hamilton** [comment]
Thanks for the response Alan! The quaternion streaming w/ the NDoF alg works properly from the mobile app.

- firmware version: 1.3.3
- hardware version: 0.1
- model number: 5 (MetaMotion R)
- serial: 00F3AF

I ran the platform on Node 4.4.7, on OS X Yosemite 10.10.5.

**Comment by alanhortz** [comment]
@hamilton

I just created a new branch regarding the configuration issue.

Would you please test this example ? https://github.com/brainexe/node-metawear/blob/issue-43/examples/sensorFusion.js

Please perform a soft reset and try again with that exact example code.

Thanks,
Alan

**Comment by hamilton** [comment]
@alanhortz The example provided appears to work.

**Comment by alanhortz** [comment]
@hamilton 

In the meantime I will investigate what happens with the configuration.

Please doesn't hesitate to advice how you would use it ...

Thanks,

Alan

**Comment by alanhortz** [comment]
@hamilton 

Glad to hear that everything seems to work fine.

I will publish a pre-release version of the 0.3.8 including the fixed example and will investigate the code to make sure the configuration does cover every sensors whatever the previous configuration could be.

I suggest you to run the same example on a different hardware, like a raspberry pi 3 for example, I have encountered slow streaming on Mac OS. 

Regards,

Thanks for your help,

Alan

**Comment by alanhortz** [comment]
example fixed in the pre-release v0.3.8-alpha.1

**Comment by hamilton** [comment]
Fantastic - thanks!
