### ISSUE TITLE
Sensor fusion does not produce any value

### ISSUE THREAD

**Issue by adekunle-A** [brainexe/node-metawear#54]
I am having trouble running the quaternion example with my Metamotion R unit. I don't have any error raised, but the data streamed are all 0s. Is the code snippet in /examples known to work at this point? The other supported examples seem to work fine.I would appreciate if you could help please

**Comment by alanhortz** [comment]
Normally it should work fine, I have produced a small example that showcase a server exposing quaternion data over a websocket for a web page to display it in 3D.

https://github.com/handsonio/metawear-3d-view

Here it is feel free to use it ...

I have extensively used the Meatwear motion R with Raspberry Pi, the following guide (a bit outdated) may help you to setup a Raspberry Zero W (inexpensive, Wifi & Bluetooth)

https://github.com/handsonio/zerow-metawear

Alan
